name: Start Server

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest 
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_URL: ${{ secrets.EC2_URL }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}

    steps:
      # Step 1: Setup SSH for EC2
      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL

      # Step 2: Start the container
      - name: Start the container
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL << 'ENDSSH'
            echo "Starting the container..."
            if [ $(docker ps -aq -f name=backend) ]; then
              echo "Removing existing container..."
              docker rm -f backend
            fi
            docker run -d -p 8000:8000 --name backend \
              -e MONGO_URL='${{ secrets.MONGO_URL }}' \
              -e PORT='${{ secrets.PORT }}' \
              -e NEXT_PUBLIC_APP_URL='${{ secrets.NEXT_PUBLIC_APP_URL }}' \
              -e RESEND_API_KEY='${{ secrets.RESEND_API_KEY }}' \
              -e COMPANY_RESEND_GMAIL_ACCOUNT='${{ secrets.COMPANY_RESEND_GMAIL_ACCOUNT }}' \
              -e ADMIN_EMAIL='${{ secrets.ADMIN_EMAIL }}' \
              -e STRIPE_SECRET_KEY='${{ secrets.STRIPE_SECRET_KEY }}' \
              -e STRIPE_WEBHOOK_SECRET='${{ secrets.STRIPE_WEBHOOK_SECRET }}' \
              -e STRIPE_PRICE_FREE='${{ secrets.STRIPE_PRICE_FREE }}' \
              -e STRIPE_PRICE_INTRO='${{ secrets.STRIPE_PRICE_INTRO }}' \
              -e STRIPE_YEARLY_PRICE_INTRO='${{ secrets.STRIPE_YEARLY_PRICE_INTRO }}' \
              -e STRIPE_PRICE_PRO='${{ secrets.STRIPE_PRICE_PRO }}' \
              -e STRIPE_YEARLY_PRICE_PRO='${{ secrets.STRIPE_YEARLY_PRICE_PRO }}' \
              -e STRIPE_FRONTEND_SUCCESS_CALLBACK='${{ secrets.STRIPE_FRONTEND_SUCCESS_CALLBACK }}' \
              -e STRIPE_FRONTEND_CANCEL_CALLBACK='${{ secrets.STRIPE_FRONTEND_CANCEL_CALLBACK }}' \
              -e AUTH_SECRET='${{ secrets.AUTH_SECRET }}' \
              -e JWT_SALT='${{ secrets.JWT_SALT }}' \
              -e FLASK_BACKEND_ML_URL='${{ secrets.FLASK_BACKEND_ML_URL }}' \
              -e AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
              -e AWS_REGION='${{ secrets.AWS_REGION }}' \
              -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
              -e AWS_BUCKET_NAME='${{ secrets.AWS_BUCKET_NAME }}' \ 
              ${{ secrets.DOCKER_USERNAME }}/backend:latest || { echo "Docker run failed"; exit 1; }
          ENDSSH